[meta]
save_dir = "exp"
seed = 3407

[finetune]
finetune = true
avg_ckpt_num = 1
ckpt_dir = "/YOUR_PATH/huggingface_hub/diarizen-wavlm-base-s80-md/pytorch_model.bin"

[trainer]
path = "trainer_dual_opt.Trainer"
[trainer.args]
max_epochs = 100
gradient_percentile = 90
gradient_history_size = 1000
save_max_score = false
save_ckpt_interval = 1
max_patience = 10
max_num_checkpoints = 100
gradient_accumulation_steps = 1
validation_interval = 1
freeze_wavlm = false
lr_decay = false
use_one_cycle_lr = false

[optimizer_small]
path = "torch.optim.AdamW"
[optimizer_small.args]
lr = 2e-5

[optimizer_big]
path = "torch.optim.AdamW"
[optimizer_big.args]
lr = 0.001

[model]
path = "diarizen.models.eend.model_wavlm_conformer_mc.Model"
[model.args]
wavlm_src = "wavlm_base_s80_md"
wavlm_layer_num = 13
wavlm_feat_dim = 768
channel_fusion_dim = 256
channel_fusion_layers = 4
channel_fusion_heads = 8
attention_in = 256
ffn_hidden = 1024
num_head = 4
num_layer = 4
dropout = 0.1
chunk_size = 8
use_posi = false
output_activate_function = false
max_speakers_per_chunk = 4
max_speakers_per_frame = 2

[train_dataset]
path = "dataset.DiarizationDataset"
[train_dataset.args]
scp_file = "data/AMI_AIS_ALI_NSF_CHiME7/train/wav.scp"
rttm_file = "data/AMI_AIS_ALI_NSF_CHiME7/train/rttm"
uem_file = "data/AMI_AIS_ALI_NSF_CHiME7/train/all.uem"
chunk_size = 8
chunk_shift = 6
sample_rate = 16000
channel_mode = "multichannel"
num_channels = 8

[train_dataset.dataloader]
batch_size = 12
num_workers = 1
drop_last = true
pin_memory = true

[validate_dataset]
path = "dataset.DiarizationDataset"
[validate_dataset.args]
scp_file = "data/AMI_AIS_ALI_NSF_CHiME7/dev/wav.scp"
rttm_file = "data/AMI_AIS_ALI_NSF_CHiME7/dev/rttm"
uem_file = "data/AMI_AIS_ALI_NSF_CHiME7/dev/all.uem"
chunk_size = 8
chunk_shift = 8
sample_rate = 16000
channel_mode = "multichannel"
num_channels = 8

[validate_dataset.dataloader]
batch_size = 16
num_workers = 1
drop_last = true
pin_memory = true
